### ISSUE TITLE
Survivor in Gladiator

### ISSUE THREAD

**Issue by Stark98** [MineKits/MineKits#402]
Hey, could we make it so you can use the Survivor Kit in gladiator boxes? At the moment you can't use the rod there.

**Comment by HDuck** [comment]
It is because the fisherman kit:
Some people flew up with phantom & fisherman to the gladiator boxes and fished them down => bug & op
Lukas has made it so that you can't fish players in the gladi boxes.

maybe @lukas81298  could make, that survivor can still use the rod in the boxes
would be great ^-^

sry for my bad english btw. xD

**Comment by Stark98** [comment]
I know, Fisherman should stay like that, but I think Survivor should be buffed so you could use the "rod power" everywhere!

**Comment by lukas81298** [comment]
Well, I'll see what I can do ;)

**Comment by lukas81298** [comment]
should be fixed now. I'll push the changes live later.
