### ISSUE TITLE
Premium on our Teamspeak

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#418]
Dear Staff

I think that all Premiums from our Server should get a few permissions on the Teamspeak.  Only a Tag for a buyed rank....  I think they should get a few advantages.

Here are some offers:

* They can use the kick permission to kick normal users/other premiums from the channel / server
* Maybe we can create some Premium Channel in the teamspeak, where only the premium members can join
* Gold and Goldplus can move users
* The Goldplus members (lifetime members) get their own private Channel on the Teamspeak (maybe there are to many premiums to do that but it should be possible) && especially the diamond users should get it. Because they have bought it in a special offer-period and there are not that many diamond-ranked users

These are only a few offers. Maybe the other staff's have some other ideas ;-)

Regards

*Scrummer*

**Comment by HDuck** [comment]
- Hmm I think this will be abused bad idea :$ (kick & move)

- Adding Donator-Channels again: 
I like it, but...
*(German sry but I can't translate it now because I have to go off ^^)*
Ich mag die Idee, aber was ist, wenn der Rang abläuft? Dann haben sie ja immernoch den Channel und nach der Zeit sind da sehr viele Channels, die nicht benutzt werden  :/
Vielleicht könnte man ja ein **vertify**-system beim TS machen (so wie beim Gomme/Rewinside Teamspeak) und wenn der Rang abläuft ist er auch im TS weg?
Und wenn ein Channel 30 Tage nicht benutzt wird wird er einfach gelöscht bzw. wenn der Channeladmin nicht mehr Donator hat? 
Dann wäre es super (wenn das geht - kenn mich mit dem TS nicht so sonderlich aus) 



- But I agree with you the Donator should have a little special permission in the TS³

**Comment by ScrummerLP** [comment]
@HDuck (I do it in german to sry xD) Also: 
* Abusen kann man den /kick und den /fly command auf dem server ja auch :^) Deswegen gibt es einfach permissionentzug bei abusing
* Die Move permission hatte ich nur gold / goldplus und diamond usern zugedacht
* Zu den channeln: Ich finde nur die lifetime-ränge (goldplus, diamond und evtl. noch iron) sollten einen Channel bekommen. Ansonsten vlt einfach 2-5 Premium Channel wo alle Premiums reinjoinen können (auch gold und emerald)
* **Das Wichtigste für alle diese Sachen ist, dass es nicht einfach 1 Premium rang gibt, sondern auch auf dem TS zwischen z.B. Emerald, diamond, gold und goldplus differenziert wird: Also verschiedene Premium ränge mit verschiedenen perms.**

Little **Example** for the Permissions:

* Iron: Can kick users & can join the Premium-Channel (Maybe own channel because its a lifetime rank)
* Emerald: Can kick users & can join Premium-Channel
* Gold: Can kick **and** move users & can join the Premium Channel
* Goldplus: Can kick **and** move users & can join the Premium Channel & gets a private Channel
* Diamond: Can kick **and** move users & can join the Premium Channel & gets a private Channel (& maybe can grant talk power because its a very special rank and there are not that many people with the rank)

*$crummer*

**Comment by lukas81298** [comment]
We won't add kick or move permissions to the teamspeak for premiums as it will be abused for sure. A premium channel is useless imo.

**Comment by ScrummerLP** [comment]
@lukas81298 why do you think so?! On our MC-Server the premiums have also the kick permissions. Maybe youcan add it only for the gold users

**Comment by EinfachNiggo** [comment]
Kick ist useless and it will be abuesed imo.
